# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: heycart-cli
    ldflags: -s -w -X 'github.com/heycart/heycart-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: shopware
    name: heycart-cli

dockers:
  # AMD64
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/amd64"

  # ARM64
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/arm64"

  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.bin
    image_templates:
      - "shopware/heycart-cli:bin-{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.bin
    image_templates:
      - "shopware/heycart-cli:bin-{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  # Shopware Docker Hub
  - name_template: shopware/heycart-cli:latest
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: shopware/heycart-cli:latest-php-8.4
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-arm64"

  - name_template: shopware/heycart-cli:latest-php-8.3
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: shopware/heycart-cli:latest-php-8.2
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: shopware/heycart-cli:latest-php-8.1
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: shopware/heycart-cli:{{ .Tag }}
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: shopware/heycart-cli:{{ .Tag }}-php-8.4
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.4-arm64"
  
  - name_template: shopware/heycart-cli:{{ .Tag }}-php-8.3
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: shopware/heycart-cli:{{ .Tag }}-php-8.2
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: shopware/heycart-cli:{{ .Tag }}-php-8.1
    image_templates:
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-amd64"
      - "shopware/heycart-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: shopware/heycart-cli:bin-{{ .Tag }}
    image_templates:
      - "shopware/heycart-cli:bin-{{ .Tag }}-amd64"
      - "shopware/heycart-cli:bin-{{ .Tag }}-arm64"

  - name_template: shopware/heycart-cli:bin
    image_templates:
      - "shopware/heycart-cli:bin-{{ .Tag }}-amd64"
      - "shopware/heycart-cli:bin-{{ .Tag }}-arm64"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: checksum
    args:
    - "sign-blob"
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - '${artifact}'
    - "--yes"

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
    - 'sign'
    - '${artifact}'
    - "--yes"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999

aurs:
  - homepage: https://developer.shopware.com/
    description: A cli which contains handy helpful commands for daily Shopware tasks
    license: MIT
    maintainers:
      - "Soner Sayakci <s.sayakci@shopware.com>"
      - "Max <max@swk-web.com>"
    private_key: '{{ .Env.AUR_KEY }}'
    commit_author:
      name: "Shopware Bot"
      email: github@shopware.com
    git_url: 'ssh://aur@aur.archlinux.org/heycart-cli-bin.git'
    depends:
      - "git"
    package: |-
      install -Dm755 "./heycart-cli" "${pkgdir}/usr/bin/heycart-cli"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/heycart-cli/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/heycart-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/heycart-cli"
      install -Dm644 "./completions/heycart-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_heycart-cli"
      install -Dm644 "./completions/heycart-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/heycart-cli.fish"

nix:
  - name: heycart-cli
    repository:
      owner: FriendsOfShopware
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_GITHUB_TOKEN }}"
    commit_author:
      name: "Shopware Bot"
      email: github@shopware.com
    post_install: |
      installShellCompletion --cmd heycart-cli \
      --bash <($out/bin/heycart-cli completion bash) \
      --zsh <($out/bin/heycart-cli completion zsh) \
      --fish <($out/bin/heycart-cli completion fish)
    homepage: "https://sw-cli.fos.gg"
    description: "Command line tool for Shopware 6"
    license: "mit"

nfpms:
  -
    package_name: heycart-cli
    vendor: "shopware AG"
    homepage: https://github.com/heycart/heycart-cli/
    maintainer: Soner Sayakci <s.sayakci@shopware.com>
    description: A cli which contains handy helpful commands for daily Shopware tasks
    license: MIT
    contents:
      - src: ./completions/heycart-cli.bash
        dst: /etc/bash_completion.d/heycart-cli
      - src: ./completions/heycart-cli.fish
        dst: /usr/share/fish/completions/heycart-cli.fish
      - src: ./completions/heycart-cli.zsh
        dst: /usr/local/share/zsh/site-functions/_heycart-cli
    formats:
      - apk
      - deb
      - rpm

brews:
  - repository:
      owner: FriendsOfShopware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    goarm: "7"
    homepage: https://friendsofshopware.com
    description: Shopware CLI helps Shopware developers manage extensions
    license: MIT
    directory: Formula
    test: |
      system "#{bin}/heycart-cli --version"
    dependencies:
    - name: node-sass
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "heycart-cli"
      bash_completion.install "completions/heycart-cli.bash" => "_heycart-cli"
      zsh_completion.install "completions/heycart-cli.zsh" => "_heycart-cli"
      fish_completion.install "completions/heycart-cli.fish"
  - repository:
      owner: shopware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN_SHOPWARE }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    goarm: "7"
    homepage: https://shopware.com
    description: Shopware CLI helps Shopware developers manage extensions
    license: MIT
    directory: Formula
    test: |
      system "#{bin}/heycart-cli --version"
    dependencies:
    - name: node-sass
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "heycart-cli"
      bash_completion.install "completions/heycart-cli.bash" => "_heycart-cli"
      zsh_completion.install "completions/heycart-cli.zsh" => "_heycart-cli"
      fish_completion.install "completions/heycart-cli.fish"

npms:
  - name: "@shopware-ag/heycart-cli"
    description: "Shopware CLI helps Shopware developers manage extensions"
    license: MIT
    homepage: https://developer.shopware.com/docs/products/cli/
    keywords:
      - cli
      - shopware
    repository: https://github.com/heycart/heycart-cli
    bugs: https://github.com/heycart/heycart-cli/issues
    access: public

notarize:
  macos:
    - enabled: '{{ isEnvSet "APPLE_CODE_SIGNING_KEY" }}'
      sign:
        certificate: "{{.Env.APPLE_CODE_SIGNING_KEY}}"
        password: "{{.Env.APPLE_CODE_SIGNING_KEY_PASSWORD}}"
        entitlements: "./entitlements.xml"
      notarize:
        issuer_id: "{{.Env.APPLE_APP_STORE_CONNECT_ISSUER}}"
        key_id: "{{.Env.APPLE_APP_STORE_CONNECT_KEY_ID}}"
        key: "{{.Env.APPLE_APP_STORE_CONNECT_KEY}}"
