# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: heycart-cli
    ldflags: -s -w -X 'github.com/heycart-org/heycart-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

nfpms:
  - id: default
    formats: [deb, rpm, apk]
    package_name: heycart-cli
    bindir: /usr/bin
    builds: [heycart-cli]
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

release:
  github:
    owner: heycart
    name: heycart-cli
    
dockers:
  # AMD64
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "heycart/heycart-cli:{{ .Tag }}-php-8.4-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "heycart/heycart-cli:{{ .Tag }}-php-8.3-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "heycart/heycart-cli:{{ .Tag }}-php-8.2-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "heycart/heycart-cli:{{ .Tag }}-php-8.1-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/amd64"
      - 
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999