name: Smoke Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # ratchet:actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          check-latest: true

      - name: Setup PHP
        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # ratchet:shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Compile heycart-cli
        run: go build

      - name: Checkout Plugin
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          repository: 'heycart/HeyPlatformDemoData'
          ref: '43dcb08fd6b5fdb7b816419494a16d2d530b3614'
          path: 'plugin'

      - name: Create HeyCart
        run: ./heycart-cli project create heycart 6.7.2.3

      - name: Build asset of Plugin
        run: ./heycart-cli extension zip plugin

      - name: Build asset of Plugin without Git
        run: ./heycart-cli extension zip plugin --disable-git --release

      - name: Validate Plugin
        run: ./heycart-cli extension validate FroshTools.zip

      - name: Get Changelog
        run: ./heycart-cli extension get-changelog FroshTools.zip

      - name: Build asset against custom PROJECT_ROOT
        env:
          SHOPWARE_PROJECT_ROOT: ${{ github.workspace }}/heycart
        run: |
          mv plugin/.heycart-extension.yml plugin/.heycart-extension-disable.yml
          ./heycart-cli extension build plugin
          mv plugin/.heycart-extension-disable.yml plugin/.heycart-extension.yml

      - name: Install a Storefront Plugin
        working-directory: heycart
        run: |
          composer require 'frosh/platform-filter-search:*' --no-interaction --no-scripts
          rm -rf vendor

      - name: Setup the project
        run: ./heycart-cli project ci heycart
